# Generated by Django 3.1.7 on 2021-05-01 19:28

from django.db import migrations, models
import uuid

from product.models import Category


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210501_2223'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Category.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
